#!/usr/bin/env bash
set -euo pipefail

# Gellop Tables — deploy.sh
# Single command to bootstrap or update the app on any Linux VPS / Raspberry Pi.
# Requires: docker, docker compose plugin.
# Tested on: Ubuntu 22.04+, Raspberry Pi OS (Bookworm), Debian 12.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Colour helpers ──────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[✓]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
err()   { echo -e "${RED}[✗]${NC} $*" >&2; }

# ── Pre-flight checks ────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  err "Docker not found. Install it first, e.g.:"
  err "  curl -fsSL https://get.docker.com | sh"
  exit 1
fi

if ! docker compose version &>/dev/null; then
  err "docker compose plugin not found (install docker-compose-plugin)."
  exit 1
fi

if ! command -v openssl &>/dev/null; then
  err "openssl not found — install it (apt install openssl)."
  exit 1
fi

# ── Generate secrets if missing ──────────────────────────────────────────────
ENV_FILE=.env
if [ ! -f "$ENV_FILE" ]; then
  warn ".env not found — generating…"
  JWT_SECRET="$(openssl rand -hex 32)"
  DB_PASS="$(openssl rand -base64 18 | tr '+/' '-_')"
  cat > "$ENV_FILE" <<EOF
# Gellop Tables — generated by deploy.sh
DB_PASS=$DB_PASS
JWT_SECRET=$JWT_SECRET
EOF
  info ".env created with random DB_PASS and JWT_SECRET"

  # Also generate backend/.env for local dev use
  sed -e "s/change…tion/$JWT_SECRET/g" \
      -e "s/clayite_pass/$DB_PASS/g" \
      -e "s/localhost:5432/db:5432/g" \
      -e "s/localhost:6379/redis:6379/g" \
      backend/.env.example > backend/.env
  info "backend/.env created"
else
  info ".env already exists — keeping it"
  # Source existing vars
  export "$(grep -v '^#' "$ENV_FILE" | xargs)"
fi

# ── Ensure DB_PASS and JWT_SECRET are in the env ────────────────────────────
export DB_PASS="${DB_PASS:-$(grep DB_PASS "$ENV_FILE" 2>/dev/null | cut -d= -f2)}"
export JWT_SECRET="${JWT_SECRET:-$(grep JWT_SECRET "$ENV_FILE" 2>/dev/null | cut -d= -f2)}"

# ── Build images ─────────────────────────────────────────────────────────────
echo ""
info "Building images (this may take a few minutes on first run)…"
docker compose build 2>&1 | tail -3

# ── Start services ──────────────────────────────────────────────────────────
echo ""
info "Starting services…"
docker compose up -d 2>&1

echo ""
info "Waiting for database to be healthy…"
# shellcheck disable=SC2034
for i in $(seq 1 30); do
  if docker compose exec -T db pg_isready -U clayite &>/dev/null; then
    info "Database is ready"
    break
  fi
  sleep 1
done

echo ""
info "Waiting for backend…"
# shellcheck disable=SC2034
for i in $(seq 1 15); do
  if docker compose exec -T app curl -sf http://localhost:3000/health &>/dev/null; then
    info "Backend is healthy"
    break
  fi
  sleep 1
done

# ── Print summary ──────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════"
info "Gellop Tables is running!"
echo ""
echo "  Frontend:  http://$(hostname -I | awk '{print $1}'):5173"
echo "  Backend:   http://$(hostname -I | awk '{print $1}'):3000"
echo ""
echo "  Quick commands:"
echo "    docker compose logs -f app         # follow backend logs"
echo "    docker compose logs -f frontend    # follow frontend logs"
echo "    make logs                          # shortcut"
echo "══════════════════════════════════════════════════════"

# ── Hint to register first user ────────────────────────────────────────────
if ! docker compose exec -T app curl -sf http://localhost:3000/api/auth/me &>/dev/null; then
  echo ""
  warn "No admin user found. Register one at:"
  echo "  http://$(hostname -I | awk '{print $1}'):5173/register"
fi
