#!/usr/bin/env bash
set -euo pipefail

# Gellop Tables — deploy.sh
# Bootstrap or update on any Linux host.
# Requires: docker + docker compose plugin.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[✓]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
err()   { echo -e "${RED}[✗]${NC} $*" >&2; }

# ── Check deps ───────────────────────────────────────────────────────────────
command -v docker &>/dev/null || { err "Docker not found. Install: curl -fsSL https://get.docker.com | sh"; exit 1; }
docker compose version &>/dev/null || { err "docker compose plugin not found"; exit 1; }
command -v openssl &>/dev/null || { err "openssl not found"; exit 1; }

# ── Generate .env if missing ──────────────────────────────────────────────────
ENV_FILE=.env
if [ ! -f "$ENV_FILE" ]; then
  warn ".env not found — generating…"
  DB_PASS="$(openssl rand -base64 18 | tr '+/' '-_')"
  JWT_SECRET="$(openssl rand -hex 32)"
  cat > "$ENV_FILE" <<EOF
# Gellop Tables — generated by deploy.sh
DB_PASS=$DB_PASS
JWT_SECRET=$JWT_SECRET
EOF
  info ".env created"

  # backend/.env for optional local dev
  sed -e "s/change-me/$JWT_SECRET/g" \
      -e "s/clayite_pass/$DB_PASS/g" \
      -e "s/localhost:5432/db:5432/g" \
      -e "s/localhost:6379/redis:6379/g" \
      backend/.env.example > backend/.env 2>/dev/null || true
  info "backend/.env created"
else
  info ".env already exists"
fi

# ── Stop old containers (free ports) ─────────────────────────────────────────
info "Stopping any existing containers…"
docker compose down --remove-orphans 2>/dev/null || true

# ── Build & start ────────────────────────────────────────────────────────────
info "Building images (first run may take a few minutes)…"
docker compose build 2>&1 | tail -1

info "Starting services…"
docker compose up -d

# ── Wait for healthy services ────────────────────────────────────────────────
info "Waiting for database…"
for i in $(seq 1 30); do
  if docker compose exec -T db env PGUSER=clayite PGPASSWORD="$(grep DB_PASS "$ENV_FILE" | cut -d= -f2)" pg_isready &>/dev/null; then
    info "Database ready"
    break
  fi
  sleep 1
done

info "Waiting for backend…"
for i in $(seq 1 20); do
  if curl -sf http://localhost:${APP_PORT:-3000}/health &>/dev/null; then
    info "Backend healthy"
    break
  fi
  sleep 1
done

# ── Summary ───────────────────────────────────────────────────────────────────
HOST_IP="$(hostname -I | awk '{print $1}')"
echo ""
echo "══════════════════════════════════════════════════════"
info "Gellop Tables is running!"
echo ""
echo "  http://${HOST_IP}:${FRONTEND_PORT:-5173}"
echo ""
echo "  Quick:   make logs   (follow logs)"
echo "══════════════════════════════════════════════════════"
